### ISSUE TITLE
Use requestAnimationFrame when possible

### ISSUE THREAD

**Issue by chmartinez** [lukelex/fader.js#8]
Really nice lib! Simple and short, as needed.

It could be a good improvement for the JS animation part to use something like requestAnimFram.
Check out http://youmightnotneedjquery.com/#fade_in as an example, and https://github.com/darius/requestAnimationFrame/blob/master/requestAnimationFrame.js as possible requestAnimationFrame polyfill.
Hope it helps!

**Comment by lukelex** [comment]
Thanks @chmartinez.
It's been a while since I last used this library. This means that I'm not really dedicating time to improve it.
If you create a Pull Request with this improvement I'd be happy to review it and add you to the project.

**Comment by lukelex** [comment]
@chmartinez Please reopen if you want to tackle this feature. Thanks for helping out :wink:
